name: Build Magisk Module

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android SDK and Build Tools
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '9477386_latest'
        packages: 'platforms;android-33'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Gradle Build
      run: ./gradlew makeZip

    - name: Upload generated ZIP
      uses: actions/upload-artifact@v4
      with:
        name: Pixelify-Magisk-Module
        path: '**/build/outputs/*.zip'
